### DISCUSSION TITLE
Refactor `work-allocator` and `worker`

### DISCUSSION THREAD

**Discussion by josecelano** [Nautilus-Cyberneering/chinese-ideographs-website#25] [General]
hi @da2ce7 @yeraydavidrodriguez the website is already using the [GitQueue action](https://github.com/Nautilus-Cyberneering/git-queue) and we need to plan the next steps.

This is a short version of the workflows we have right now:

### Work allocator:

```yml
name: Work allocator
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Debug env vars                             <-- DEBUG
      - uses: actions/checkout@v2                        <-- checkout
      - name: Set up git committer identity              <-- git config
      - name: Get next job                               <-- git-queue action 
      - name: Update submodule to get new commit ref     <-- new generic or embedded action?
      - name: Build job message payload                  <-- new generic or embedded action?
      - name: Debug step outputs                         <-- DEBUG
      - name: Create new job                             <-- git-queue action
      - name: Show new git-queue commit                  <-- DEBUG
      - name: Push new job to the queue                  <-- git push  
```

### Worker:

```yml
name: Worker

on:
  push:
    branches: [main]
  schedule:
    - cron: "0,10,20,30,40,50 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Debug env vars                             <-- DEBUG
      - uses: actions/checkout@v2                        <-- checkout
      - name: Set up git committer identity              <-- git config
      - name: Get next job                               <-- git-queue action 
      - name: Parse job payload                          <-- new generic or embedded action?
      - name: Build job started message payload          <-- git-queue action
      - name: Mark job as started                        <-- git-queue action

        # Begin mutual exclusion job

      - name: Update submodule                            <-- new generic or embedded action?
      - name: Commit submodule update
      - name: Setup DVC         
      - name: Dvc diff for library                        <-- DEBUG
      - name: Pull dataset from remote                    <-- new generic or Librarian action?

        # Step only for this website project 
      - name: Sync images from media library to this repo <-- new generic or Librarian action?
      - name: Resize synched imaged                       <-- new generic or Librarian action?
      - name: Change file format of synched images        <-- new generic or Librarian action?
      - name: Remove unneeded base images
      - name: Show added or modified Base Images
      - name: Archive images
        # TODO: one commits per image
      - name: Apply all changes with a single commit      <-- new generic or Librarian action?
      - name: Debug auto-commit output                    <-- DEBUG
        # End steps only for this website project 

        # End mutual exclusion job

      - name: Build job finished message payload          <-- new generic or embedded action?
      - name: Mark job as finished                        <-- git-queue action
      - name: Debug step outputs                          <-- DEBUG
      - name: Show new commits                            <-- DEBUG
      - name: Push                                        <-- git push
      
        # Publish web
      - name: Build website if Base images have been added
      - name: Deploy website if Base images have been added
```

As you can see we have replaced some embedded action with the GitQueue action. I would like to review all the pending tasks and how we are going to implement them.

### TODO

- [x] I'm not signing the bot commits because it seems there is a [bug](https://github.com/crazy-max/ghaction-import-gpg/issues/119#issuecomment-1050066795) if you want to upload only the subkey.
- [ ] I've deleted the embedded auto-commit action because It was using the github API and we decided not to use it because we have more conflicts and complexity working with the runner and remote branch at the same time. And because the final merge is not atomic. I've added a step that commits all changes in `public/images` folder with a single commit. Maybe that's fine for the website and we do not need here a different commit for each change.
- [ ] Once we publish the GitQueue version 1.0.0 we have to update the workflows.
- [ ] @da2ce7 proposed to sign commits at the end of the workflows.
- [ ] We have some bash scripts, embedded action that potentially could be converted to Librarian commands or generic actions. I'm going to describe those refactors in the next section. We have to decide which of them we want to implement.

### Refactors

There are different kinds of steps:

1. GitQue
2. Handle the queue messages: build and parse the job payload
3. Handle git submodules updates: update and only get the potential update information. I mean, there is a step to check it there is something to update in the library.
4. Steps related to image manipulation that could be potentially converted to Librarian commands or generic GitHub Actions.
5. Step specific for this website project.

I'm going to write down the list of new actions and their responsibility:

### New actions (embedded, Librarian commands or generic)

Names are temporary :-)

`git-submodule-message-builder`:

- It builds and parsers the payload of a submodule update job.
- I think this one can be a generic action.

`git-submodule-update`:

- It returns the previous and current git ref if we applied a submodule update.
- It updates a git submodule to a given ref.
- I think this one can be a generic action.

`selective-dvc-pull`:

- It pulls a list of files from dvc remote storage.
- I think this can be a Librarian command.

`sync-images-from-media-library`:

- Given a DVD diff it syncs the files with a local repo directory. Bash script: `sync-base-images.sh`.
- I think this can be a Librarian command. The librarian helps to get changes and put them in a given temp folder. Then you can process those files as you want.

`resize-images:

- I think this can be a Librarian command.

`change-file-format`:

- I think this can be a Librarian command.

That could be all if we do not want to create a commit for each change.

Maybe `git-submodule-update` and `git-submodule-message-builder` could be merged in a single action. But we can use a [composite action](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action) later.

This is going to be a lot of work @da2ce7 so maybe we have to consider if we have other priorities before implementing these reactors.

**Comment by josecelano** [comment]
hi @da2ce7 @yeraydavidrodriguez I would like to continue working on the worker but I think it would be better if we have a discussion before I start. For example, I wanted to start creating a new command for the Librarian to pull files from dvc storage. I would like to replace this step in the `worker`:

```
- name: Pull dataset from remote
  if: ${{ steps.get-next-job.outputs.job_found == 'true' }}
  run: cd library && dvc pull --remote azure && cd ..
  env:
    AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
    AZURE_STORAGE_SAS_TOKEN: ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}
```

I'm not sure if the input should be directly the dvc diff json or a plain file path list. My idea is to convert this Librarian action:

https://github.com/Nautilus-Cyberneering/nautilus-librarian/blob/main/src/nautilus_librarian/typer/commands/workflows/actions/dvc_pull_action.py

into its own command. We only need to wrap the action (kind of workflow step) with a new Typer command, so that we can use that action independently from the Gold Processing command. That action only pulls new and modified files because we do not need the deleted or modified ones. Is that OK for you?

The alternative could be to create a new generic Typescript action to pull files from remote DVC storage.

I think It makes more sense the first one because all tasks are related to image dataset management And our focus is not building a generic wrapper for the DVC.

If you think that is OK I can start with that and then discuss other changes later or in the meantime in working on this.
