### ISSUE TITLE
Trigger workflow to import Base images from library repository

### ISSUE THREAD

**Issue by josecelano** [Nautilus-Cyberneering/chinese-ideographs-website#10]
Relates to: https://github.com/Nautilus-Cyberneering/chinese-ideographs/issues/102

We want to trigger the [`import-base-images.yml`](https://github.com/Nautilus-Cyberneering/chinese-ideographs-website/blob/main/.github/workflows/import-base-images.yml) workflow remotely from the [library repo](https://github.com/Nautilus-Cyberneering/chinese-ideographs/).

In order to do that we need to change the workflow to add the new event:

```
on: 
  workflow_dispatch:
    inputs:
      library_sha:
        description: 'The library commit sha that triggered the workflow'     
        required: true
```
