### ISSUE TITLE
Sign Git Queue commits

### ISSUE THREAD

**Issue by josecelano** [Nautilus-Cyberneering/chinese-ideographs-website#30]
Commits created by the Git Queue action are not being signed.

![image](https://user-images.githubusercontent.com/58816/156736455-43d7099a-bc0a-4693-849d-542986fc4327.png)

That's because [by default](https://github.com/Nautilus-Cyberneering/git-queue/blob/main/action.yml#L25) the git queue does not sign the commits.

@da2ce7 proposed to sign them at the end of the workflow with a commit amend.

It can be done with a rebase: https://superuser.com/a/1123928/277693

Until we implement that final solution we just can enable signing when using the git-queue action:

```yml
- name: Create new job
  id: create-job
  if: ${{ steps.get-next-job.outputs.job_found == 'false' && steps.update-submodule.outputs.updated == 'true' }}
  uses: Nautilus-Cyberneering/git-queue@v1-beta
  with:
    queue_name: "library-update"
    action: "create-job"
    job_payload: "${{ steps.build-payload.outputs.payload }}"
    git_commit_gpg_sign: "true"
```

We have to do it with all steps using the action.
