### ISSUE TITLE
Selective dvc pull

### ISSUE THREAD

**Issue by josecelano** [Nautilus-Cyberneering/chinese-ideographs-website#4]
In the current [workflow to import Base images](https://github.com/Nautilus-Cyberneering/chinese-ideographs-website/blob/main/.github/workflows/import-base-images.yml) from the library (git submodule) we always pull all images from DVC storage: 

```
      - name: Pull dataset from remote
        run: cd library && dvc pull --remote azure && cd ..
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_SAS_TOKEN: ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}
```

We should only get the new or modified Base images. We can use the output from the previous step to get the list of new and modified images.

```
      - name: Dvc diff for library
        id: library-dvc-diff
        run: ./scripts/library-dvc-diff.sh
        env:
          DVC_REPO_DIR: "library"
          PREVIOUS_REF: ${{ steps.update-library.outputs.previous_ref }}
          CURRENT_REF: ${{ steps.update-library.outputs.current_ref }}
```

The dvc-diff step gives us all the changes in the library between our current version and the latest library version. Then we have to filter that list to get only changes related to Base images.
